@startuml

hide empty members
object "forest 0" as forest_0
object "tree 0" as tree_0
object "cave 0" as cave_0
object "tree 1" as tree_1
object "tree 2" as tree_2
object "root 0" as root_0
forest_0 -- tree_0
forest_0 -- tree_1
forest_0 -- tree_2
cave_0 -- forest_0
root_0 -- cave_0

@enduml